[workspace]
members = [
    "guessing_game",
    "enum_test",
    "match_test",
    "lib_test",
    "lib_main_test",
    "collections_test",
    "file_read",
    "struct_test",
    "trait_test",
    "cli_func",
    "hashmap_test",
    "t_test",
    "url_htmm2md",
    "rhttp",
    "mysql_test"
]